name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
      
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8.12.1
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: pnpm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}